Repository IUMusicalFish19/Visual-Circuit-Designer, pull requests merged in 2025-07, with the labels that each got.

#132 Tests
  .gitignore
  .idea/jsLibraryMappings.xml
  UI/babel.config.cjs
  UI/jest.config.cjs
  UI/package-lock.json
  UI/package.json
  UI/src/components/pages/mainPage.jsx
  UI/src/components/utils/__tests__/deselectAll.util.test.js
  UI/src/components/utils/__tests__/getSelectedElements.unit.test.js
  UI/src/components/utils/__tests__/isValidConnection.unit.test.js
  UI/src/components/utils/__tests__/selectAll.util.test.js
  UI/src/components/utils/flowHelpers.js
Labels: enhancement

#143 tabs
  UI/src/App.jsx
  UI/src/CSS/circuitsMenu.css
  UI/src/CSS/index.css
  UI/src/CSS/settings.css
  UI/src/CSS/tabs.css
  UI/src/components/codeComponents/edges.js
  UI/src/components/codeComponents/nodes.js
  UI/src/components/pages/mainPage.jsx
  UI/src/components/pages/mainPage/hotkeys-handler.js
  UI/src/components/pages/mainPage/local-save.jsx
  UI/src/components/pages/mainPage/settings.jsx
  UI/src/components/pages/mainPage/switch.jsx
  UI/src/components/pages/mainPage/tabs.jsx
  UI/src/components/pages/mainPage/toolbar.jsx
Labels: enhancement

#145 Frontend integration/unit tests
  .github/workflows/frontend_tests.yml
  UI/jest.config.cjs
  UI/src/components/pages/mainPage.jsx
  UI/src/components/pages/mainPage/loadLocalStorage.jsx
  UI/src/components/pages/mainPage/useHotkeys.js
  UI/src/components/utils/__tests__/integration tests/runnerConnection.test.js
  UI/src/components/utils/__tests__/unit tests/deleteSelected.util.test.js
  UI/src/components/utils/__tests__/unit tests/deselectAll.util.test.js
  UI/src/components/utils/__tests__/unit tests/getSelectedElements.unit.test.js
  UI/src/components/utils/__tests__/unit tests/hotkeyHandler.unit.test.js
  UI/src/components/utils/__tests__/unit tests/isValidConnection.unit.test.js
  UI/src/components/utils/__tests__/unit tests/selectAll.util.test.js
  UI/src/components/utils/deleteSelected.js
  UI/src/components/utils/deselectAll.js
  UI/src/components/utils/flowHelpers.js
  UI/src/components/utils/getSelected.js
  UI/src/components/utils/hotkeyHandler.js
  UI/src/components/utils/isValidConnection.js
  UI/src/components/utils/selectAll.js
Labels: enhancement

#146 Unit tests
  UI/jest.config.cjs
  UI/src/components/codeComponents/NodeContextMenu.jsx
  UI/src/components/constants/nodeSizes.js
  UI/src/components/constants/numbers.js
  UI/src/components/pages/mainPage.jsx
  UI/src/components/pages/mainPage/loadLocalStorage.jsx
  UI/src/components/utils/__tests__/unit tests/calculateContextMenuPosition.unit.test.js
  UI/src/components/utils/__tests__/unit tests/calculateDropPosition.unit.test.js
  UI/src/components/utils/__tests__/unit tests/copyElements.unit.test.js
  UI/src/components/utils/__tests__/unit tests/cutElements.unit.test.js
  UI/src/components/utils/__tests__/unit tests/deleteSelected.util.test.js
  UI/src/components/utils/__tests__/unit tests/deleteSelectedElements.unit.test.js
  UI/src/components/utils/__tests__/unit tests/deselectAll.unit.test.js
  UI/src/components/utils/__tests__/unit tests/getClosestEdge.unit.test.js
  UI/src/components/utils/__tests__/unit tests/getSelectedElements.unit.test.js
  UI/src/components/utils/__tests__/unit tests/loadCircuit.unit.test.js
  UI/src/components/utils/__tests__/unit tests/loadLocalStorage.unit.test.js
  UI/src/components/utils/__tests__/unit tests/onDrop.unit.test.js
  UI/src/components/utils/__tests__/unit tests/onNodeDragStop.unit.test.js
  UI/src/components/utils/__tests__/unit tests/pasteElements.unit.test.js
  UI/src/components/utils/__tests__/unit tests/saveCircuit.unit.test.js
  UI/src/components/utils/__tests__/unit tests/selectAll.unit.test.js
  UI/src/components/utils/__tests__/unit tests/spawnCircuit.unit.test.js
  UI/src/components/utils/calculateContextMenuPosition.js
  UI/src/components/utils/calculatePosition.js
  UI/src/components/utils/copyElements.js
  UI/src/components/utils/cutElements.js
  UI/src/components/utils/deleteSelected.js
  UI/src/components/utils/deleteSelectedElements.js
  UI/src/components/utils/getClosestEdge.js
  UI/src/components/utils/getSelectedElements.js
  UI/src/components/utils/hotkeyHandler.js
  UI/src/components/utils/loadCircuit.js
  UI/src/components/utils/loadLocalStorage.js
  UI/src/components/utils/onDrop.js
  UI/src/components/utils/onNodeDragStop.js
  UI/src/components/utils/pasteElements.js
  UI/src/components/utils/saveCircuit.js
  UI/src/components/utils/spawnCircuit.js
Labels: enhancement

#154 Undo redo
  .github/ISSUE_TEMPLATE/AC_template.md
  UI/assets/ui-icons.jsx
  UI/package-lock.json
  UI/package.json
  UI/src/CSS/circuitsMenu.css
  UI/src/CSS/dnd.css
  UI/src/CSS/toolbar.css
  UI/src/CSS/variables.css
  UI/src/components/pages/mainPage.jsx
  UI/src/components/pages/mainPage/tabs.jsx
  UI/src/components/pages/mainPage/toolbar.jsx
  UI/src/components/utils/__tests__/unit tests/createHistoryUpdater.unit.test.js
  UI/src/components/utils/__tests__/unit tests/handleTabSwitch.unit.test.js
  UI/src/components/utils/__tests__/unit tests/initializeTabHistory.unit.test.js
  UI/src/components/utils/__tests__/unit tests/redo.unit.test.js
  UI/src/components/utils/__tests__/unit tests/undo.unit.test.js
  UI/src/components/utils/calculateContextMenuPosition.js
  UI/src/components/utils/createHistoryUpdater.js
  UI/src/components/utils/handleTabSwitch.js
  UI/src/components/utils/hotkeyHandler.js
  UI/src/components/utils/initializeTabHistory.js
  UI/src/components/utils/onNodeDragStop.js
  UI/src/components/utils/redo.js
  UI/src/components/utils/undo.js
Labels: enhancement

#162 README.md and docs update
  CONTRIBUTING.md
  README.md
  UI/src/components/utils/__tests__/integration_tests/runnerConnection.test.js
  docs/architecture/architecture.md
  docs/architecture/static-view/static-view.png
  docs/automation/continuous-delivery.md
  docs/automation/continuous-integration.md
  docs/logo.png
  docs/quality-assurance/automated-tests.md
  docs/quality-assurance/user-acceptance-tests.md
  docs/quality-attributes/quality-attribute-scenarios.md
  docs/usage/projectContextDiagram.png
Labels: enhancement

#164 Changelog
  CHANGELOG.md
Labels: enhancement

#160 Button names and tabs fixes
  UI/src/CSS/App.css
  UI/src/CSS/circuitsMenu.css
  UI/src/CSS/index.css
  UI/src/CSS/tabs.css
  UI/src/components/pages/mainPage.jsx
  UI/src/components/pages/mainPage/circuitsMenu.jsx
  UI/src/components/pages/mainPage/tabs.jsx
  UI/src/components/pages/mainPage/toolbar.jsx
Labels: enhancement

#172 Profile API
  UI/src/CSS/auth.css
  UI/src/CSS/profile.css
  UI/src/CSS/reg.css
  UI/src/components/pages/auth.jsx
  UI/src/components/pages/mainPage.jsx
  UI/src/components/pages/mainPage/runnerHandler.jsx
  UI/src/components/pages/register.jsx
  backend/Dockerfile
  backend/__init__.py
  backend/auth/__init__.py
  backend/auth/config.py
  backend/auth/db.py
  backend/auth/main.py
  backend/auth/models.py
  backend/auth/schema.py
  backend/auth/users/__init__.py
  backend/auth/users/manager.py
  backend/auth/users/mongo_users.py
  backend/profile/__init__.py
  backend/profile/database/__init__.py
  backend/profile/database/db.py
  backend/profile/database/pgre_projects.py
  backend/profile/database/pgre_users.py
  backend/profile/main.py
  backend/profile/models.py
  backend/profile/routers/__init__.py
  backend/profile/routers/profile.py
  backend/profile/routers/project.py
  backend/profile/schemas.py
  backend/profile/utils.py
  backend/requirements.txt
  backend/tests/auth_test/__init__.py
  backend/tests/auth_test/conftest.py
  backend/tests/auth_test/test_delete_user.py
  backend/tests/auth_test/test_get_curr_user.py
  backend/tests/auth_test/test_login.py
  backend/tests/auth_test/test_login_wrong_password.py
  backend/tests/auth_test/test_password_validation.py
  backend/tests/auth_test/test_protection.py
  backend/tests/auth_test/test_register.py
  backend/tests/auth_test/test_register_invalid_email.py
  backend/tests/auth_test/test_registered_duplicate_email.py
  backend/tests/auth_test/test_registered_duplicate_username.py
  backend/tests/auth_test/test_update_user.py
  backend/tests/auth_test/test_verify_token.py
  backend/tests/profile_tests/__init__.py
  backend/tests/profile_tests/conftest.py
  backend/tests/profile_tests/test_create_project.py
  backend/tests/profile_tests/test_delete.py
  backend/tests/profile_tests/test_get_forbidden_project.py
  backend/tests/profile_tests/test_get_info.py
  backend/tests/profile_tests/test_get_projects.py
  backend/tests/profile_tests/test_update_email.py
  backend/tests/profile_tests/test_update_name.py
  backend/tests/profile_tests/test_update_project.py
  docker-compose.yml
  postgres-init/users.sql
Labels: enhancement, backend

#175 authFrontend
  UI/src/CSS/auth.css
  UI/src/CSS/reg.css
  UI/src/components/pages/auth.jsx
  UI/src/components/pages/register.jsx
  auth/src/api/AuthRequestHandlerFactory.cpp
Labels: enhancement, frontend

#176 Fix postgres initdb order
  postgres-init/1-users.sql
  postgres-init/2-projects.sql
Labels: bug, backend

#177 Fix runner url
  UI/src/components/pages/mainPage/runnerHandler.jsx
Labels: bug, frontend

#178 Fix postgres health-check timer
  docker-compose.yml
Labels: bug, backend

#181 try to fix login and registration(wrong link)v.2
  UI/src/components/pages/auth.jsx
  UI/src/components/pages/register.jsx
Labels: bug

#184 Custom nodes frontend
  UI/assets/circuits-icons.jsx
  UI/assets/toolbar-icons.jsx
  UI/src/App.jsx
  UI/src/CSS/app.css
  UI/src/CSS/auth.css
  UI/src/CSS/circuits-menu.css
  UI/src/CSS/customBlock.css
  UI/src/CSS/reg.css
  UI/src/CSS/toolbar.css
  UI/src/components/circuits/advancedElements/TextNode.jsx
  UI/src/components/circuits/customBlockNode.jsx
  UI/src/components/codeComponents/PaneContextMenu.jsx
  UI/src/components/codeComponents/logger.jsx
  UI/src/components/codeComponents/nodes.js
  UI/src/components/pages/auth.jsx
  UI/src/components/pages/mainPage.jsx
  UI/src/components/pages/mainPage/FlowWithCustomNodes.jsx
  UI/src/components/pages/mainPage/circuitsMenu.jsx
  UI/src/components/pages/mainPage/createCustomBlockModal.jsx
  UI/src/components/pages/mainPage/customCircuit.jsx
  UI/src/components/pages/mainPage/toolbar.jsx
  UI/src/components/utils/__tests__/unit tests/customBlockUtils.unit.test.js
  UI/src/components/utils/__tests__/unit tests/hotkeyHandler.unit.test.js
  UI/src/components/utils/customBlockUtils.js
  UI/src/components/utils/hotkeyHandler.js
  UI/src/components/utils/onDrop.js
  UI/src/components/utils/spawnCircuit.js
Labels: enhancement

#186 fixed
  UI/src/components/pages/mainPage.jsx
Labels: bug

#187 Fix frontend build
  UI/src/components/codeComponents/nodes.js
Labels: bug, frontend
